name: Daily arXiv Update

on:
  schedule:
    # Run at 8:00 UTC every day
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allow manual triggering
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run arXiv monitor
        run: python arxiv_monitor.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'Wang Jianghai'
          git config --global user.email 'jianghai001@e.ntu.edu.sg'
          git add README.md data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update arXiv papers: $(date +'%Y-%m-%d')" && git push)